[package]
name = "hypermash"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/jianshu93/hypermash"
keywords = ["genome", "MinHash", "sketch"]
license = "MIT OR Apache-2.0"
description = "Genome/Metagenome sketching via HyperMinHash"

[dependencies]
clap = "4.3"
needletail = "0.6.0"
rayon = "1.5"
crossbeam-channel = "0.5"
xxhash-rust = "0.8"
hyperminhash = "0.1.3"
log = { version = "0.4" }
env_logger = { version = "0.11" }
